---
version: 2
jobs:
  build:
    docker:
      - image: dickeyxxx/cli-engine-docker:v1.3.1
    working_directory: ~/cli-plugin
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "yarn.lock" }}
            - node-modules-
      - run: yarn
      - run: jest --coverage && bash <(curl -s https://codecov.io/bash)
      - run: flow check
      - run: eslint .
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - /usr/local/share/.cache/yarn
